import type { NextPage } from 'next'
import Head from 'next/head'

import IndexPage from './index_remix'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <IndexPage />

    </>
  )
}

export default Home
